collapse_pre_releases: false
stop_at_branch_base: true
sections:
  # The prelude section is implicitly included.
  - [features, New Features]
  - [issues, Known Issues]
  - [upgrade, Upgrade Notes]
  - [api, API Changes]
  - [security, Security Issues]
  - [fixes, Bug Fixes]
# Change prelude_section_name to 'release_summary' from default value
# 'prelude'.
prelude_section_name: release_summary
template: |
          issues:
            List known issues here, or remove this section.
encoding: utf8

